Repository monta-app/github-workflows, pull requests merged in 2024-09, with the labels that each got.

#103 feat(sonar): Ensure coverage task is run if present
  .github/workflows/sonar-cloud.yaml
Labels: missing-jira, XS review

#104 feat: incroduces workflows for auto-creating release PRs (PS-442)
  .github/workflows/monta-merge-command.yaml
  .github/workflows/production-pr.yaml
  .github/workflows/release-tag.yaml
  .github/workflows/staging-pr.yaml
  README.md
Labels: S review

#105 feat: remove if condition from monta-merge-command (PS-442)
  .github/workflows/monta-merge-command.yaml
Labels: XS review

#106 feat: enable `more-power` input variable for github hosted deploys too
  .github/workflows/deploy.yaml
Labels: missing-jira, XS review

#107 chore: update readme (PS-442)
  README.md
Labels: XS review

#108 feat(deploy): Restrict production deployments to main/master (PS-487)
  .github/workflows/deploy.yaml
Labels: XS review

#109 Revert "feat(deploy): Restrict production deployments to main/master …
  .github/workflows/deploy.yaml
Labels: missing-jira, XS review
